export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export EDITOR="vim"
export HISTSIZE=1000000 # Set history size
export SAVEHIST=$HISTSIZE # Save history after logout
export HISTFILE="$HOME/.zsh_history"

# macOS exports
export PATH="/usr/local/sbin:$PATH"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk/Contents/Home"
export GPG_TTY=$(tty) # For gpg on macOS

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

export PATH="$HOME/.fastlane/bin:$PATH"
