export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export EDITOR="vim"
export HISTSIZE=1000000 # Set history size
export SAVEHIST=$HISTSIZE # Save history after logout
export HISTFILE="$HOME/.zsh_history"

# macOS exports
export PATH="/usr/local/sbin:$PATH"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/openjdk-21.jdk/Contents/Home"
export GPG_TTY=$(tty) # For gpg on macOS
